from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator 


# model for vault entites
class Cluster(models.Model):
    cluster_name = models.CharField(max_length=64, blank=True, null=True, unique=True)
    entities_count = models.IntegerField(blank=True, null=True)
    entities_metadata = models.CharField(max_length=256, blank=True, null=True)
    threshold = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(999999)], blank=True, null=True)
    node1 = models.URLField(max_length = 256, blank=True, null=True)
    node2 = models.URLField(max_length = 256, blank=True, null=True)
    node3 = models.URLField(max_length = 256, blank=True, null=True)
    node4 = models.URLField(max_length = 256, blank=True, null=True)
    node5 = models.URLField(max_length = 256, blank=True, null=True)
    node6 = models.URLField(max_length = 256, blank=True, null=True)
    node7 = models.URLField(max_length = 256, blank=True, null=True)
    node8 = models.URLField(max_length = 256, blank=True, null=True)
    node9 = models.URLField(max_length = 256, blank=True, null=True)
    node10 = models.URLField(max_length = 256, blank=True, null=True)
    node11 = models.URLField(max_length = 256, blank=True, null=True)
    node12 = models.URLField(max_length = 256, blank=True, null=True)
    node13 = models.URLField(max_length = 256, blank=True, null=True)
    node14 = models.URLField(max_length = 256, blank=True, null=True)
    node15 = models.URLField(max_length = 256, blank=True, null=True)
    node16 = models.URLField(max_length = 256, blank=True, null=True)
    node17 = models.URLField(max_length = 256, blank=True, null=True)
    node18 = models.URLField(max_length = 256, blank=True, null=True)
    node19 = models.URLField(max_length = 256, blank=True, null=True)
    node20 = models.URLField(max_length = 256, blank=True, null=True)
    node21 = models.URLField(max_length = 256, blank=True, null=True)
    node22 = models.URLField(max_length = 256, blank=True, null=True)
    node23 = models.URLField(max_length = 256, blank=True, null=True)
    node24 = models.URLField(max_length = 256, blank=True, null=True)
    node25 = models.URLField(max_length = 256, blank=True, null=True)
    node26 = models.URLField(max_length = 256, blank=True, null=True)
    node27 = models.URLField(max_length = 256, blank=True, null=True)
    node28 = models.URLField(max_length = 256, blank=True, null=True)
    node29 = models.URLField(max_length = 256, blank=True, null=True)
    node30 = models.URLField(max_length = 256, blank=True, null=True)
    node31 = models.URLField(max_length = 256, blank=True, null=True)
    node32 = models.URLField(max_length = 256, blank=True, null=True)
    node33 = models.URLField(max_length = 256, blank=True, null=True)
    node34 = models.URLField(max_length = 256, blank=True, null=True)
    node35 = models.URLField(max_length = 256, blank=True, null=True)
    node36 = models.URLField(max_length = 256, blank=True, null=True)
    node37 = models.URLField(max_length = 256, blank=True, null=True)
    node38 = models.URLField(max_length = 256, blank=True, null=True)
    node39 = models.URLField(max_length = 256, blank=True, null=True)
    node40 = models.URLField(max_length = 256, blank=True, null=True)
    node41 = models.URLField(max_length = 256, blank=True, null=True)
    node42 = models.URLField(max_length = 256, blank=True, null=True)
    node43 = models.URLField(max_length = 256, blank=True, null=True)
    node44 = models.URLField(max_length = 256, blank=True, null=True)
    node45 = models.URLField(max_length = 256, blank=True, null=True)
    node46 = models.URLField(max_length = 256, blank=True, null=True)
    node47 = models.URLField(max_length = 256, blank=True, null=True)
    node48 = models.URLField(max_length = 256, blank=True, null=True)
    node49 = models.URLField(max_length = 256, blank=True, null=True)
    node50 = models.URLField(max_length = 256, blank=True, null=True)

    def __str__(self):
        return str(self.cluster_name)


class Job(models.Model):
    email = models.EmailField(blank=True, null=True, unique=True)
    cc = models.EmailField(blank=True, null=True, unique=True)
    cc2 = models.EmailField(blank=True, null=True, unique=True)
    cc3 = models.EmailField(blank=True, null=True, unique=True)
    cluster_name = models.ForeignKey(Cluster, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)
